/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiPushVapidKeyRouteImport } from './routes/api/push/vapid-key'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPublicBotTickRouteImport } from './routes/api/public/bot-tick'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidKeyRoute = ApiPushVapidKeyRouteImport.update({
  id: '/api/push/vapid-key',
  path: '/api/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTickRoute = ApiPublicBotTickRouteImport.update({
  id: '/api/public/bot-tick',
  path: '/api/public/bot-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth'
    | '/api/session'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth'
    | '/api/session'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-key'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/auth'
    | '/api/session'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  ApiPublicBotTickRoute: typeof ApiPublicBotTickRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiPushVapidKeyRoute: typeof ApiPushVapidKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-key': {
      id: '/api/push/vapid-key'
      path: '/api/push/vapid-key'
      fullPath: '/api/push/vapid-key'
      preLoaderRoute: typeof ApiPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot-tick': {
      id: '/api/public/bot-tick'
      path: '/api/public/bot-tick'
      fullPath: '/api/public/bot-tick'
      preLoaderRoute: typeof ApiPublicBotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof ApiAuthRoute
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  ApiPublicBotTickRoute: ApiPublicBotTickRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiPushVapidKeyRoute: ApiPushVapidKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
